PRODUCT = ref_soft.dll
INSTLOCATION =

SRC = $(BASEPATH)game/q_shared.c r_aclip.c r_alias.c r_bsp.c r_draw.c r_edge.c r_image.c \
      r_light.c r_main.c r_misc.c r_model.c r_part.c r_poly.c r_polyse.c \
      r_rast.c r_scan.c r_sprite.c r_surf.c \
      $(BASEPATH)amiga/q_shamiga.c $(BASEPATH)amiga/sw_imp.c

OBJ = $(SRC:.c=.o)

include /amiga/config.mk
